networks:
  sea:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
services:
  undercover:
    container_name: bonny
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_SUBNET: ""
      INTERNAL_VPN_ADDRESS: ""
      VPN_PRIVATE_KEY: ""
      VPN_DNS: ""
      VPN_PUBLIC_KEY: ""
      VPN_ENDPOINT: ""
      VPN_PORT: ""
      MONGODB_ENDPOINT: ""
    volumes:
      - ./server:/home/runner/server
    ports:
      - 8000:8000
    user: 1000:1000
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      - net.ipv6.conf.eth0.disable_ipv6=1
    privileged: true
    depends_on:
      - database
    networks:
      sea:
        ipv4_address: 172.21.0.3
  database:
    container_name: bonny_db
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    networks:
      sea:
        ipv4_address: 172.21.0.2