services:
  undercover:
    container_name: bonny
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SUBNET: "172.17.0.0/16"
        ROUTER_SUBNET: "192.168.178.0/24"
        DNS_ADDRESSES: "162.252.172.57,149.154.159.92"
        VPN_ENDPOINT: "185.188.61.42"
        VPN_PORT: "51820"
    volumes:
      - ./:/home/runner/app
    ports:
      - 8000:8000
    user: 1000:1000
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
      - net.ipv6.conf.eth0.disable_ipv6=1
    privileged: true